### ISSUE TITLE
Any plans to make this extensible

### ISSUE THREAD

**Issue by plaindocs** [mapbox/retext-mapbox-standard#12]
It seems pretty mapbox centric, I'm wondering if you're planning to make it more extensible so people can easily switch off mapbox stuff, swap in some other default config, and still be able to easily install/update.

**Comment by guilhermesimoes** [comment]
You mean https://github.com/wooorm/retext?

**Comment by plaindocs** [comment]
Yes actually. I was under the mistaken impression that the original software was mapbox-retext, not wooorm. Thanks! :-)

**Comment by wooorm** [comment]
@plaindocs I’m not original software, I’m a human being! 😢

But in all seriousness, retext-mapbox-standard already is Mapbox stuff on top of other, easily installable and updatable software; I believe this issue can be closed.
