### ISSUE TITLE
Fix bug around word 'length'

### ISSUE THREAD

**Issue by tmcw** [mapbox/retext-mapbox-standard#5]
This triggers a lol-worthy error which has a guessable cause.

**Comment by wooorm** [comment]
Maybe [here](https://github.com/mapbox/retext-mapbox-standard/blob/78edbf899a4fb59c0a0ff338e6cecf9d15011b16/index.js#L21), which should be `{}` instead of `[]` (if I’m reading that code correctly?)

**Comment by tmcw** [comment]
Ah! Yep, that's it thanks! 31e1bf53d3709034aff5e9391989aa532d4c9d09
