### ISSUE TITLE
Grunt plugin?

### ISSUE THREAD

**Issue by franciscop** [mapbox/retext-mapbox-standard#9]
Awesome project, thanks for making it open source. I'd love to integrate it in my workflow, is there any plan to [build a Grunt plugin](http://gruntjs.com/creating-plugins)? I can see this becoming really useful for many open source projects

**Comment by tmcw** [comment]
We'd certainly accept a PR implementing this feature. We don't use Grunt at Mapbox, so it's unlikely any of us will build this ourselves or know the right idioms to build it.
